### PR TITLE
Addition of dates to entities (disease, grant, license, material, software), addition of genome_location_schema, added genomic locations and related entity to molecular entity, added keywords to study groups

### PR DESCRIPTION
**Pull request by agbeltran**

### CODE REVIEW

**Comment by agbeltran** [comment]
I've merged this PR with master, bringing in the new changes. 

The current changes in this PR are:

- addition of 'licenses' property to DATS.Dimension
- addition of 'dates' property, allowing for description of different types of dates, to schemas for Disease, Grant, License, Material, Software
- addition of 'keywords' property to StudyGroup
- addition of 'genomic_location_schema'
- addition of 'genomicLocations', using the corresponding schema, to MolecularEntity.
- addition of 'relatedEntities' to MolecularEntity, generalising the previous solution for relatedMolecularEntities - this pattern for relatedEntities could be used in other entities if necessary, but we haven't got a use case for this yet. In that case, a new entity would become useful to support reuse

**Comment by agbeltran** [comment]
After discussions with @aegururaj, I'm including further changes in the molecular entity schema, to include a description field and expand the evidence information (including multiple evidence codes and associated publications).

**Comment by agbeltran** [comment]
Discussion with @jonathancrabtree about changing licenses in Dimension schema to include consent information instead.

**Comment by agbeltran** [comment]
I believe this PR is ready to be merged unless there are more comments? @proccaserra @jonathancrabtree @aegururaj

**Review by jonathancrabtree — APPROVED** [review]
Looks good to me!

**Review by proccaserra — APPROVED** [review]

**Pull request merged**
