### PR TITLE
Proposed solution to model consent and license information

### PR DESCRIPTION
**Pull request by agbeltran**

### CODE REVIEW

**Review by proccaserra — CHANGES_REQUESTED** [review]
overall changes in agreement with the discussion held and evolving the initial proposal pushed to the data-use branch.
on consent schema: correction to some of the 'description' fields:
e.g. change "Information about consent information, which may be applicable at different levels." to "an object to describe consent information and provide relevant consent codes. Consent information schema can refer to one or more License object(s) and can be used to annotate Dats.Material , for fine grained control, or Dats.StudyGroup for coarser annotation).
I would rename 'name' to 'consentCodes' and link to an array of annotation_schema. (as information going into 'name' could go into 'description' element of the schema.
Also change the description from 'the name of the consent information, including a label and ideally an ontology term', to  'one or more code from resources such as DUO, ADA-M'.

typo+changes to 'isDescribedInLicenses' description:
from "A reference to the licenses that thake into account the consent information." to " a list of reference to licences/ legal documents used as basis for extract ing consent information summary and assigning one or more consent codes.

**Comment by agbeltran** [comment]
In the consent_information_schema I followed the pattern name/abbreviation/description as per the [table in the Consent Codes paper](http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1005772) where name is an annotation, so the name (value) and if available, the IRI of the term describing it (valueIRI). In this case, the schema represents a single consent code, and materials and study group include arrays whose items are consent_info_schemas.

**Comment by agbeltran** [comment]
We may consider renaming ```consent_info_schema``` as ```consent_code_schema```.

**Comment by agbeltran** [comment]
Descriptions fields changed.

**Comment by agbeltran** [comment]
Request by @altergc: change 'isDescribedInLicenses' to 'incorporatedIn'.

**Review by proccaserra — COMMENTED** [review]
the 'name','abbreviation','description' is specific to the paper. using 'name' here departs from the average use of the tag 'name' in DATS. 'consent codes' with their 'name' and 'identifier' match the 'value/valueIRI from the DATS.annotation_schema, so having 'consentCode' instead of 'name' IMHO seems clearer

**Comment by altergc** [comment]
Here is an example of a Data Use Limitation (DUL) as it is used in dbGAP.
How would you tag these properties?

   "Health/Medical/Biomedical" 
   "HMB"
   "Use of the data is limited to health/medical/biomedical purposes, does not include the study of population origins or ancestry."

At the moment, there is no ontology for this.  They are described in a pdf:
https://osp.od.nih.gov/wp-content/uploads/standard_data_use_limitations.pdf

**Comment by agbeltran** [comment]
This dbGAP DUL would be represented as:

(case 1)
```
{
 "name": {
    "value": "Health/Medical/Biomedical"
  },
 "abbreviation": "HMB"
 "description": "Use of the data is limited to health/medical/biomedical purposes, does not include the study of population origins or ancestry."
}
```

As not always there is an ontology term (or systematic code), I though that ```name``` was more appropriate than ```code```.

If there was an ontology term, it would go in ```valueIRI```, e.g.:

(case 2)
```
{
 "name": {
    "value": "Health/Medical/Biomedical",
     "valueIRI": "http://ontology.com/ontologyTermIRI"
  },
 "abbreviation": "HMB"
 "description": "Use of the data is limited to health/medical/biomedical purposes, does not include the study of population origins or ancestry."
}
```

Alternatively, we could have name as a string and use the identifier for the IRI:

(case 3)
```
{
  "identifier": "http://ontology.com/ontologyTermIRI"
 "name": "Health/Medical/Biomedical",
 "abbreviation": "HMB"
 "description": "Use of the data is limited to health/medical/biomedical purposes, does not include the study of population origins or ancestry."
}
```
but in this case, we would be adding more information than the ontology term (e.g. link to licenses) so I wouldn't use the ontology term as the identifier.

**Comment by proccaserra** [comment]
would the following be an option
{
"value": "Health/Medical/Biomedical",
"valueIRI:"http://ontology.com/ontologyTermIRI"
 "abbreviation": "HMB"
 "description": "Use of the data is limited to health/medical/biomedical purposes, does not include the study of population origins or ancestry."
}

which is essential case 3 with labels  trying to reuse an existing pattern/motif we have from 'dats.annotation_schema', ?

**Comment by agbeltran** [comment]
This option would change the way we use the annotation_schema in the rest of the entities, where we say what attribute we are annotating.

**Comment by agbeltran** [comment]
Request by @proccaserra: change 'approvers' to 'licensingAuthority'

**Review by proccaserra — COMMENTED** [review]
@agbeltran just spotted a minor oversight in consent_info_schema.json.
change
"@type": { "type": "string", "enum": [ "License" ]},
to 
"@type": { "type": "string", "enum": [ "Consent Information" ]},

**Comment by agbeltran** [comment]
Fixed! Thanks.

**Comment by agbeltran** [comment]
I believe this is ready to be merged, unless there are more comments @proccaserra @altergc ?

**Pull request merged**
